"""adding protheus_last_synced_at

Revision ID: 2bd98a5925c0
Revises: c6ac26a53b55
Create Date: 2026-05-05 16:40:51.855963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd98a5925c0'
down_revision: Union[str, Sequence[str], None] = 'c6ac26a53b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedor_on_proteus', sa.Column('protheus_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fornecedor_on_proteus', 'protheus_last_synced_at')
    # ### end Alembic commands ###
