"""adding cep column on fornecedor_on_proteus table

Revision ID: 60bc60c86a25
Revises: b4d14fe0784c
Create Date: 2026-05-05 15:58:11.218421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bc60c86a25'
down_revision: Union[str, Sequence[str], None] = 'b4d14fe0784c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedor_on_proteus', sa.Column('cep', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fornecedor_on_proteus', 'cep')
    # ### end Alembic commands ###
