"""adding fornecedor_on_protheus table

Revision ID: b4d14fe0784c
Revises: b58e3fe2b304
Create Date: 2026-05-05 15:03:04.376714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d14fe0784c'
down_revision: Union[str, Sequence[str], None] = 'b58e3fe2b304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_on_proteus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('to_update', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('protheus_synced_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedor_on_proteus_id'), 'fornecedor_on_proteus', ['id'], unique=False)
    op.create_index(op.f('ix_fornecedor_on_proteus_id_fornecedor'), 'fornecedor_on_proteus', ['id_fornecedor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fornecedor_on_proteus_id_fornecedor'), table_name='fornecedor_on_proteus')
    op.drop_index(op.f('ix_fornecedor_on_proteus_id'), table_name='fornecedor_on_proteus')
    op.drop_table('fornecedor_on_proteus')
    # ### end Alembic commands ###
