"""adding municipios table

Revision ID: f1e2d3c4b5a6
Revises: 2bd98a5925c0
Create Date: 2026-05-12 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e2d3c4b5a6'
down_revision: Union[str, Sequence[str], None] = '2bd98a5925c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_name', sa.String(), nullable=False),
    sa.Column('codigo_ibge', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_ibge')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    # ### end Alembic commands ###
